markdown: kramdown
markdown_ext:  markdown,mkd,mkdn,md
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: aakosp
author: "张良"
email: aakosp#gmail.com
name: "张良个人博客"
baseurl: /
all_categories: [
["android", "Android开发","/posts/android.html"], 
["program", "软件编程","/posts/program.html"],
["web", "Web建站","/posts/web.html"], 
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "/posts/page:num"
timezone: America/Los_Angeles
sitesource: /blog

collections:
  docs:
    output: true

gems:
 - jekyll-paginate

theme: jekyll-theme-time-machine